---
galaxy_info:
  role_name: alloy
  author: Conscia - Observability (adapted from grafana.grafana.alloy)
  description: Install and configure Grafana Alloy with multi-config directory support
  license: "Apache-2.0"
  min_ansible_version: "2.13"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Windows
      versions:
        - "2016"
        - "2019"
        - "2022"
  galaxy_tags:
    - alloy
    - grafana
    - observability
    - monitoring
