---
- name: Restart alloy
  listen: "restart alloy"
  ansible.builtin.systemd:
    daemon_reload: true
    name: alloy.service
    state: restarted
    enabled: true
  when:
    - not ansible_check_mode
    - ansible_facts['os_family'] != 'Windows'

- name: Restart alloy windows
  listen: "restart alloy windows"
  ansible.windows.win_service:
    name: Alloy
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_facts['os_family'] == 'Windows'
